name: EC2 Connection Test

on:
  workflow_dispatch:

jobs:
  connect:
    runs-on: ubuntu-latest
    steps:
      - name: SSH into EC2
        uses: appleboy/ssh-action@master
        with:
          host: ${{ secrets.EC2_HOST }}
          username: ${{ secrets.EC2_USERNAME }}
          key: ${{ secrets.EC2_SSH_KEY }}
          script: |
            whoami
            pwd
            echo "Hello from EC2!"
